[package]
name = "ryguessr"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
dotenvy = "0.15.7"
env_logger = "0.11.9"
log = "0.4.29"
rand = "0.10.0"
reqwest = { version = "0.13.2" }
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["full"] }
